<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "restaurant_mheptlsmbkebdm"
 *
 * Auto generated by Extension Builder 2020-05-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Restaurant MHEPTLSMBKEBDM',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Matteo HEVIN, Eloi PELOUX, Elie BOURY , Thomas LE SAUX, Marwane BENOU-KAISS, Dorian MORAX',
    'author_email' => 'matteo.hevin@etu.u-bordeaux.fr, eloi.ac@etu.u-bordeaux.fr, elie.boury@etu.u-bordeaux.fr, thomas.le-saux@etu.u-bordeaux.fr, marwane.benou-kaiss@etu.u-bordeaux.fr, dorian.morax@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
